import Layout from "@/components/Layout";
export const metadata = {
    title: 'Employee',
    description: 'Generated by create next app',
  }

 
  export default function EmployeeLayout({ children }) {
    return <Layout>{children}</Layout> 
  }

  