import Layout from "@/components/Layout";
export const metadata = {
  title: 'Post',
  description: 'Generated by create next app',
}


export default function PostLayout({ children }) {
  return <Layout>{children}</Layout> 
}

