import Layout from "@/components/Layout";
export const metadata = {
    title: 'Item',
    description: 'Generated by create next app',
  }

 
  export default function ItemLayout({ children }) {
    return <Layout>{children}</Layout>
  }

  